# Generated by Django 2.2.5 on 2019-12-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupPolicies',
            fields=[
                ('id_policy', models.BigIntegerField(primary_key=True, serialize=False)),
                ('policy_name', models.CharField(blank=True, max_length=150, null=True)),
                ('backup_type', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=8)),
                ('minute', models.CharField(max_length=100)),
                ('hour', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('day_week', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('size_backup', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=8)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'backup_policies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id_client', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CronDay',
            fields=[
                ('id_policy', models.BigIntegerField(primary_key=True, serialize=False)),
                ('day', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cron_day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CronDayWeek',
            fields=[
                ('id_policy', models.BigIntegerField(primary_key=True, serialize=False)),
                ('day_week', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cron_day_week',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CronHour',
            fields=[
                ('id_policy', models.BigIntegerField(primary_key=True, serialize=False)),
                ('hour', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cron_hour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CronMinute',
            fields=[
                ('id_policy', models.BigIntegerField(primary_key=True, serialize=False)),
                ('minute', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cron_minute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CronMonth',
            fields=[
                ('id_policy', models.BigIntegerField(primary_key=True, serialize=False)),
                ('month', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cron_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CronYear',
            fields=[
                ('id_policy', models.BigIntegerField(primary_key=True, serialize=False)),
                ('year', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cron_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id_database', models.BigIntegerField(primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('last_resync', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('dbid', models.FloatField()),
            ],
            options={
                'db_table': 'databases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id_host', models.FloatField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=15)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hosts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id_policy', models.BigIntegerField(primary_key=True, serialize=False)),
                ('schedule_start', models.DateField()),
            ],
            options={
                'db_table': 'schedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.FloatField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamps', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwBackupPolicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_policy', models.BigIntegerField()),
                ('schedule_start', models.DateField()),
                ('hostname', models.CharField(max_length=100)),
                ('db_name', models.CharField(max_length=20)),
                ('dbid', models.FloatField()),
                ('destination', models.CharField(max_length=8)),
                ('backup_type', models.CharField(max_length=30)),
                ('duration', models.FloatField()),
                ('size_backup', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'vw_backup_policies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwRmanBackupJobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=8)),
                ('dbid', models.FloatField()),
                ('db_key', models.FloatField()),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=23, null=True)),
                ('time_taken_display', models.CharField(blank=True, max_length=4000, null=True)),
                ('output_bytes_display', models.CharField(blank=True, max_length=4000, null=True)),
                ('output_device_type', models.CharField(blank=True, max_length=17, null=True)),
                ('session_key', models.FloatField(blank=True, null=True)),
                ('session_recid', models.FloatField(blank=True, null=True)),
                ('session_stamp', models.FloatField(blank=True, null=True)),
                ('input_type', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'vw_rman_backup_job_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwRmanBackupSubjobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=8)),
                ('dbid', models.FloatField()),
                ('operation', models.CharField(blank=True, max_length=33, null=True)),
                ('input_type', models.CharField(blank=True, max_length=13, null=True)),
                ('status', models.CharField(blank=True, max_length=23, null=True)),
                ('session_stamp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_rman_backup_subjob_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwRmanDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_key', models.FloatField()),
                ('dbinc_key', models.FloatField(blank=True, null=True)),
                ('dbid', models.FloatField()),
                ('name', models.CharField(max_length=8)),
                ('resetlogs_change_field', models.FloatField(db_column='resetlogs_change#')),
                ('resetlogs_time', models.DateField()),
            ],
            options={
                'db_table': 'vw_rman_database',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwRmanOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_key', models.FloatField()),
                ('session_key', models.FloatField()),
                ('recid', models.FloatField()),
                ('stamp', models.FloatField()),
                ('output', models.CharField(max_length=130)),
            ],
            options={
                'db_table': 'vw_rman_output',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwRmanStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_key', models.FloatField()),
                ('db_name', models.CharField(max_length=8)),
                ('row_level', models.FloatField(blank=True, null=True)),
                ('operation', models.CharField(blank=True, max_length=33, null=True)),
                ('object_type', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(blank=True, max_length=33, null=True)),
                ('session_key', models.IntegerField(blank=True, null=True)),
                ('session_recid', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_rman_status',
                'managed': False,
            },
        ),
    ]
