# Generated by Django 5.2.4 on 2025-08-01 04:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VwBackupPolicies',
            fields=[
                ('id_policy', models.BigIntegerField(primary_key=True, serialize=False)),
                ('schedule_start', models.DateTimeField()),
                ('hostname', models.CharField(max_length=100)),
                ('db_name', models.CharField(max_length=20)),
                ('dbid', models.BigIntegerField()),
                ('destination', models.CharField(max_length=8)),
                ('backup_type', models.CharField(max_length=30)),
                ('duration', models.DecimalField(decimal_places=0, max_digits=10)),
                ('size_backup', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'vw_backup_policies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwRmanBackupJobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=8)),
                ('dbid', models.BigIntegerField()),
                ('db_key', models.BigIntegerField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=23, null=True)),
                ('time_taken_display', models.CharField(blank=True, max_length=4000, null=True)),
                ('output_bytes_display', models.CharField(blank=True, max_length=4000, null=True)),
                ('output_device_type', models.CharField(blank=True, max_length=17, null=True)),
                ('session_key', models.BigIntegerField(blank=True, null=True)),
                ('session_recid', models.BigIntegerField(blank=True, null=True)),
                ('session_stamp', models.BigIntegerField(blank=True, null=True)),
                ('input_type', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'vw_rman_backup_job_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='RelbackUser',
            fields=[
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('status', models.PositiveSmallIntegerField(default=1, help_text='1 = Active, 2 = Inactive', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id_host', models.BigAutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='coreRelback.client')),
                ('created_by', models.ForeignKey(db_column='created_id_user', on_delete=django.db.models.deletion.PROTECT, related_name='created_hosts', to='coreRelback.relbackuser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_id_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_hosts', to='coreRelback.relbackuser')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'db_table': 'hosts',
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id_database', models.BigAutoField(primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('last_resync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dbid', models.BigIntegerField()),
                ('client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='coreRelback.client')),
                ('host', models.ForeignKey(db_column='id_host', on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='coreRelback.host')),
                ('created_by', models.ForeignKey(db_column='created_id_user', on_delete=django.db.models.deletion.PROTECT, related_name='created_databases', to='coreRelback.relbackuser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_id_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_databases', to='coreRelback.relbackuser')),
            ],
            options={
                'verbose_name': 'Banco de Dados',
                'verbose_name_plural': 'Bancos de Dados',
                'db_table': 'databases',
                'unique_together': {('id_database', 'client', 'host')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(db_column='created_id_user', on_delete=django.db.models.deletion.PROTECT, related_name='created_clients', to='coreRelback.relbackuser'),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_id_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_clients', to='coreRelback.relbackuser'),
        ),
        migrations.CreateModel(
            name='BackupPolicy',
            fields=[
                ('id_policy', models.BigAutoField(primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=150)),
                ('backup_type', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=8)),
                ('minute', models.CharField(max_length=100)),
                ('hour', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('day_week', models.CharField(max_length=100)),
                ('duration', models.DecimalField(decimal_places=0, max_digits=10)),
                ('size_backup', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=8)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='backup_policies', to='coreRelback.client')),
                ('database', models.ForeignKey(db_column='id_database', on_delete=django.db.models.deletion.CASCADE, related_name='backup_policies', to='coreRelback.database')),
                ('host', models.ForeignKey(db_column='id_host', on_delete=django.db.models.deletion.CASCADE, related_name='backup_policies', to='coreRelback.host')),
                ('created_by', models.ForeignKey(db_column='created_id_user', on_delete=django.db.models.deletion.PROTECT, related_name='created_backup_policies', to='coreRelback.relbackuser')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_id_user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_backup_policies', to='coreRelback.relbackuser')),
            ],
            options={
                'verbose_name': 'Política de Backup',
                'verbose_name_plural': 'Políticas de Backup',
                'db_table': 'backup_policies',
            },
        ),
        migrations.CreateModel(
            name='CronDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('backup_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_days', to='coreRelback.backuppolicy')),
            ],
            options={
                'verbose_name': 'Cron (Dia)',
                'verbose_name_plural': 'Cron (Dias)',
                'db_table': 'cron_day',
                'unique_together': {('backup_policy', 'day')},
            },
        ),
        migrations.CreateModel(
            name='CronDayWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_week', models.PositiveSmallIntegerField()),
                ('backup_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_day_weeks', to='coreRelback.backuppolicy')),
            ],
            options={
                'verbose_name': 'Cron (Dia da Semana)',
                'verbose_name_plural': 'Cron (Dias da Semana)',
                'db_table': 'cron_day_week',
                'unique_together': {('backup_policy', 'day_week')},
            },
        ),
        migrations.CreateModel(
            name='CronHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveSmallIntegerField()),
                ('backup_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_hours', to='coreRelback.backuppolicy')),
            ],
            options={
                'verbose_name': 'Cron (Hora)',
                'verbose_name_plural': 'Cron (Horas)',
                'db_table': 'cron_hour',
                'unique_together': {('backup_policy', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='CronMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveSmallIntegerField()),
                ('backup_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_minutes', to='coreRelback.backuppolicy')),
            ],
            options={
                'verbose_name': 'Cron (Minuto)',
                'verbose_name_plural': 'Cron (Minutos)',
                'db_table': 'cron_minute',
                'unique_together': {('backup_policy', 'minute')},
            },
        ),
        migrations.CreateModel(
            name='CronMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('backup_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_months', to='coreRelback.backuppolicy')),
            ],
            options={
                'verbose_name': 'Cron (Mês)',
                'verbose_name_plural': 'Cron (Meses)',
                'db_table': 'cron_month',
                'unique_together': {('backup_policy', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CronYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('backup_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_years', to='coreRelback.backuppolicy')),
            ],
            options={
                'verbose_name': 'Cron (Ano)',
                'verbose_name_plural': 'Cron (Anos)',
                'db_table': 'cron_year',
                'unique_together': {('backup_policy', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id_schedule', models.BigAutoField(primary_key=True, serialize=False)),
                ('schedule_start', models.DateTimeField()),
                ('backup_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='coreRelback.backuppolicy')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'db_table': 'schedules',
                'unique_together': {('backup_policy', 'schedule_start')},
            },
        ),
    ]
