# Generated by Django 5.2.4 on 2025-08-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreRelback', '0001_initial'),
    ]

    operations = [
    ]
