# Generated by Django 5.2 on 2025-04-13 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreRelback', '0003_create_sequences_triggers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VwRmanBackupJobDetails',
        ),
        migrations.AlterUniqueTogether(
            name='cronday',
            unique_together={('backup_policy', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='crondayweek',
            unique_together={('backup_policy', 'day_week')},
        ),
        migrations.AlterUniqueTogether(
            name='cronhour',
            unique_together={('backup_policy', 'hour')},
        ),
        migrations.AlterUniqueTogether(
            name='cronminute',
            unique_together={('backup_policy', 'minute')},
        ),
        migrations.AlterUniqueTogether(
            name='cronmonth',
            unique_together={('backup_policy', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='cronyear',
            unique_together={('backup_policy', 'year')},
        ),
        migrations.AddField(
            model_name='cronday',
            name='backup_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cron_days', to='coreRelback.backuppolicy'),
        ),
        migrations.AddField(
            model_name='cronday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='crondayweek',
            name='backup_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cron_day_weeks', to='coreRelback.backuppolicy'),
        ),
        migrations.AddField(
            model_name='crondayweek',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='cronhour',
            name='backup_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cron_hours', to='coreRelback.backuppolicy'),
        ),
        migrations.AddField(
            model_name='cronhour',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='cronminute',
            name='backup_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cron_minutes', to='coreRelback.backuppolicy'),
        ),
        migrations.AddField(
            model_name='cronminute',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='cronmonth',
            name='backup_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cron_months', to='coreRelback.backuppolicy'),
        ),
        migrations.AddField(
            model_name='cronmonth',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='cronyear',
            name='backup_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cron_years', to='coreRelback.backuppolicy'),
        ),
        migrations.AddField(
            model_name='cronyear',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cronday',
            name='day',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='crondayweek',
            name='day_week',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cronhour',
            name='hour',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cronminute',
            name='minute',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cronmonth',
            name='month',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cronyear',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.RemoveField(
            model_name='cronday',
            name='id_policy',
        ),
        migrations.RemoveField(
            model_name='crondayweek',
            name='id_policy',
        ),
        migrations.RemoveField(
            model_name='cronhour',
            name='id_policy',
        ),
        migrations.RemoveField(
            model_name='cronminute',
            name='id_policy',
        ),
        migrations.RemoveField(
            model_name='cronmonth',
            name='id_policy',
        ),
        migrations.RemoveField(
            model_name='cronyear',
            name='id_policy',
        ),
    ]
