# Generated by Django 5.2.4 on 2025-08-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreRelback', '0004_delete_vwrmanbackupjobdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relbackuser',
            name='theme_preference',
            field=models.CharField(
                choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], 
                default='light', 
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='relbackuser',
            name='language_preference',
            field=models.CharField(
                choices=[('en', 'English'), ('pt', 'Portuguese')], 
                default='en', 
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='relbackuser',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
