# Generated by Django 5.2.4 on 2025-08-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreRelback', '0002_auto_20250801_1426'),
        ('coreRelback', '0004_delete_vwrmanbackupjobdetails_and_more'),
    ]

    operations = [
    ]
