"""
Django settings for projectRelback project.

Generated by 'django-admin startproject' using Django 5.2.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import logging
import os
import shutil

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "kd7pxh^@fij*g0tj*rwsw-ps$ckpay^7t@!tbinj0>j3vhxr"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'daphne',  # ASGI server (Phase 18) — must be before django.contrib
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'django_browser_reload',
    'coreRelback',
    'django_tables2',
    'rest_framework',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projectRelback.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",           # Templates globais
            BASE_DIR / "coreRelback/templates" # Templates do app
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # incluído uma única vez
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'coreRelback.context_processors.relback_user',  # Context processor customizado
            ],
        },
    },
]

WSGI_APPLICATION = 'projectRelback.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
""" DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
} """

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': '192.168.124.139:1521/cobaia',
        'USER': 'relback',
        'PASSWORD': 'relback',
        'TEST': {
            'MIRROR': 'default',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Use BigAutoField as the default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Backend de autenticação customizado
AUTHENTICATION_BACKENDS = [
    'coreRelback.backends.RelbackUserBackend',
    'django.contrib.auth.backends.ModelBackend',  # fallback
]

# URLs de redirecionamento após login/logout
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# ---------------------------------------------------------------------------
# Tailwind CSS + DaisyUI
# ---------------------------------------------------------------------------
TAILWIND_APP_NAME = 'theme'

# Required for django-tailwind live-reload in development
INTERNAL_IPS = [
    '127.0.0.1',
]

NPM_BIN_PATH = shutil.which('npm') or '/usr/bin/npm'

# ---------------------------------------------------------------------------
# 🛡️  Runtime guard — warn (don't crash) if Tailwind CSS has not been compiled.
# Protects the WSGI process on staging/production when 'tailwind build' was
# not executed before deployment.  The shipped placeholder is < 100 bytes.
# ---------------------------------------------------------------------------
_TAILWIND_DIST_CSS = BASE_DIR / 'theme' / 'static' / 'css' / 'dist' / 'styles.css'
_theme_logger = logging.getLogger('relback.theme')
# 4 096 bytes: any real Tailwind build (even --minify) comfortably exceeds this.
# The placeholder comment file ships at ~200 bytes, so this catches it reliably.
if not _TAILWIND_DIST_CSS.exists() or _TAILWIND_DIST_CSS.stat().st_size < 4096:
    _theme_logger.warning(
        "Tailwind CSS not compiled: '%s' is missing or a placeholder. "
        "Run: python manage.py tailwind install && python manage.py tailwind build",
        _TAILWIND_DIST_CSS,
    )

# ---------------------------------------------------------------------------
# Guard live-reload middleware: inject ONLY in debug mode to avoid routing
# overhead and 404 noise on production/staging.
# ---------------------------------------------------------------------------
if DEBUG:
    MIDDLEWARE.insert(1, 'django_browser_reload.middleware.BrowserReloadMiddleware')

# ---------------------------------------------------------------------------
# Oracle RMAN Recovery Catalog connection (read-only, separate from Django DB)
#
# Set ORACLE_CATALOG = None in settings_dev.py / settings_test.py to skip.
# In production, override via environment variables so credentials are never
# committed to version control.
# ---------------------------------------------------------------------------
import os as _os

ORACLE_CATALOG: dict | None = {
    "user":     _os.environ.get("ORACLE_CATALOG_USER",     "relback"),
    "password": _os.environ.get("ORACLE_CATALOG_PASSWORD", "relback"),
    "dsn":      _os.environ.get("ORACLE_CATALOG_DSN",      "192.168.124.139:1521/cobaia"),
}

# ---------------------------------------------------------------------------
# Django REST Framework — API layer (Phase 17)
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# ---------------------------------------------------------------------------
# Django Channels — WebSocket / ASGI (Phase 18)
# ---------------------------------------------------------------------------
ASGI_APPLICATION = "projectRelback.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}
